// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: src/verifier/verifier.proto

package verifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OfferPlatformCertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatformCert []byte `protobuf:"bytes,1,opt,name=platformCert,proto3" json:"platformCert,omitempty"`
}

func (x *OfferPlatformCertRequest) Reset() {
	*x = OfferPlatformCertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferPlatformCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferPlatformCertRequest) ProtoMessage() {}

func (x *OfferPlatformCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferPlatformCertRequest.ProtoReflect.Descriptor instead.
func (*OfferPlatformCertRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{0}
}

func (x *OfferPlatformCertRequest) GetPlatformCert() []byte {
	if x != nil {
		return x.PlatformCert
	}
	return nil
}

type OfferPlatformCertResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OfferPlatformCertResponse) Reset() {
	*x = OfferPlatformCertResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferPlatformCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferPlatformCertResponse) ProtoMessage() {}

func (x *OfferPlatformCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferPlatformCertResponse.ProtoReflect.Descriptor instead.
func (*OfferPlatformCertResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{1}
}

type OfferEKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EkCert []byte `protobuf:"bytes,1,opt,name=ekCert,proto3" json:"ekCert,omitempty"`
}

func (x *OfferEKRequest) Reset() {
	*x = OfferEKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferEKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferEKRequest) ProtoMessage() {}

func (x *OfferEKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferEKRequest.ProtoReflect.Descriptor instead.
func (*OfferEKRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{2}
}

func (x *OfferEKRequest) GetEkCert() []byte {
	if x != nil {
		return x.EkCert
	}
	return nil
}

type OfferEKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OfferEKResponse) Reset() {
	*x = OfferEKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferEKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferEKResponse) ProtoMessage() {}

func (x *OfferEKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferEKResponse.ProtoReflect.Descriptor instead.
func (*OfferEKResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{3}
}

type OfferAKRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttestationParameters []byte `protobuf:"bytes,1,opt,name=attestation_parameters,json=attestationParameters,proto3" json:"attestation_parameters,omitempty"`
}

func (x *OfferAKRequest) Reset() {
	*x = OfferAKRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferAKRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferAKRequest) ProtoMessage() {}

func (x *OfferAKRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferAKRequest.ProtoReflect.Descriptor instead.
func (*OfferAKRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{4}
}

func (x *OfferAKRequest) GetAttestationParameters() []byte {
	if x != nil {
		return x.AttestationParameters
	}
	return nil
}

type OfferAKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OfferAKResponse) Reset() {
	*x = OfferAKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferAKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferAKResponse) ProtoMessage() {}

func (x *OfferAKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferAKResponse.ProtoReflect.Descriptor instead.
func (*OfferAKResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{5}
}

type GetMakeCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMakeCredentialRequest) Reset() {
	*x = GetMakeCredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMakeCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMakeCredentialRequest) ProtoMessage() {}

func (x *GetMakeCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMakeCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetMakeCredentialRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{6}
}

type GetMakeCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EncryptedCredentials []byte `protobuf:"bytes,1,opt,name=encrypted_credentials,json=encryptedCredentials,proto3" json:"encrypted_credentials,omitempty"`
}

func (x *GetMakeCredentialResponse) Reset() {
	*x = GetMakeCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMakeCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMakeCredentialResponse) ProtoMessage() {}

func (x *GetMakeCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMakeCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetMakeCredentialResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{7}
}

func (x *GetMakeCredentialResponse) GetEncryptedCredentials() []byte {
	if x != nil {
		return x.EncryptedCredentials
	}
	return nil
}

type SetActivateCredentialRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Secret []byte `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
}

func (x *SetActivateCredentialRequest) Reset() {
	*x = SetActivateCredentialRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetActivateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActivateCredentialRequest) ProtoMessage() {}

func (x *SetActivateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActivateCredentialRequest.ProtoReflect.Descriptor instead.
func (*SetActivateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{8}
}

func (x *SetActivateCredentialRequest) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

type SetActivateCredentialResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetActivateCredentialResponse) Reset() {
	*x = SetActivateCredentialResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetActivateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetActivateCredentialResponse) ProtoMessage() {}

func (x *SetActivateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetActivateCredentialResponse.ProtoReflect.Descriptor instead.
func (*SetActivateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{9}
}

type OfferQuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OfferQuoteRequest) Reset() {
	*x = OfferQuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferQuoteRequest) ProtoMessage() {}

func (x *OfferQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferQuoteRequest.ProtoReflect.Descriptor instead.
func (*OfferQuoteRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{10}
}

type OfferQuoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nonce []byte `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
}

func (x *OfferQuoteResponse) Reset() {
	*x = OfferQuoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfferQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferQuoteResponse) ProtoMessage() {}

func (x *OfferQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferQuoteResponse.ProtoReflect.Descriptor instead.
func (*OfferQuoteResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{11}
}

func (x *OfferQuoteResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type SetQuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlatformAttestation []byte `protobuf:"bytes,1,opt,name=platform_attestation,json=platformAttestation,proto3" json:"platform_attestation,omitempty"`
}

func (x *SetQuoteRequest) Reset() {
	*x = SetQuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQuoteRequest) ProtoMessage() {}

func (x *SetQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQuoteRequest.ProtoReflect.Descriptor instead.
func (*SetQuoteRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{12}
}

func (x *SetQuoteRequest) GetPlatformAttestation() []byte {
	if x != nil {
		return x.PlatformAttestation
	}
	return nil
}

type SetQuoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetQuoteResponse) Reset() {
	*x = SetQuoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetQuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetQuoteResponse) ProtoMessage() {}

func (x *SetQuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetQuoteResponse.ProtoReflect.Descriptor instead.
func (*SetQuoteResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{13}
}

type SetAttestedKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key              []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	KeyCertification []byte `protobuf:"bytes,2,opt,name=keyCertification,proto3" json:"keyCertification,omitempty"`
}

func (x *SetAttestedKeyRequest) Reset() {
	*x = SetAttestedKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAttestedKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttestedKeyRequest) ProtoMessage() {}

func (x *SetAttestedKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttestedKeyRequest.ProtoReflect.Descriptor instead.
func (*SetAttestedKeyRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{14}
}

func (x *SetAttestedKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SetAttestedKeyRequest) GetKeyCertification() []byte {
	if x != nil {
		return x.KeyCertification
	}
	return nil
}

type SetAttestedKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetAttestedKeyResponse) Reset() {
	*x = SetAttestedKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetAttestedKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAttestedKeyResponse) ProtoMessage() {}

func (x *SetAttestedKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAttestedKeyResponse.ProtoReflect.Descriptor instead.
func (*SetAttestedKeyResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{15}
}

type GetCertificateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Csr []byte `protobuf:"bytes,1,opt,name=csr,proto3" json:"csr,omitempty"`
}

func (x *GetCertificateRequest) Reset() {
	*x = GetCertificateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateRequest) ProtoMessage() {}

func (x *GetCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateRequest.ProtoReflect.Descriptor instead.
func (*GetCertificateRequest) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{16}
}

func (x *GetCertificateRequest) GetCsr() []byte {
	if x != nil {
		return x.Csr
	}
	return nil
}

type GetCertificateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Certificate []byte `protobuf:"bytes,1,opt,name=certificate,proto3" json:"certificate,omitempty"`
}

func (x *GetCertificateResponse) Reset() {
	*x = GetCertificateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_verifier_verifier_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertificateResponse) ProtoMessage() {}

func (x *GetCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_verifier_verifier_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertificateResponse.ProtoReflect.Descriptor instead.
func (*GetCertificateResponse) Descriptor() ([]byte, []int) {
	return file_src_verifier_verifier_proto_rawDescGZIP(), []int{17}
}

func (x *GetCertificateResponse) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

var File_src_verifier_verifier_proto protoreflect.FileDescriptor

var file_src_verifier_verifier_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x72, 0x63, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2f, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x76,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x18, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43,
	0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x70, 0x6c, 0x61, 0x74, 0x66,
	0x6f, 0x72, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x45, 0x4b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x6b, 0x43, 0x65, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x6b, 0x43, 0x65, 0x72, 0x74, 0x22, 0x11,
	0x0a, 0x0f, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x45, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x47, 0x0a, 0x0e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x41, 0x4b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x16, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x15, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x11, 0x0a, 0x0f, 0x4f, 0x66,
	0x66, 0x65, 0x72, 0x41, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x0a,
	0x18, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6b, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x50, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x6b, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x15, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x65, 0x64, 0x5f, 0x63, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x14, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x22, 0x36, 0x0a, 0x1c, 0x53,
	0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x22, 0x1f, 0x0a, 0x1d, 0x53, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x12, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x22, 0x44, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x14, 0x70, 0x6c, 0x61, 0x74,
	0x66, 0x6f, 0x72, 0x6d, 0x5f, 0x61, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x12, 0x0a, 0x10, 0x53,
	0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x55, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x2a, 0x0a, 0x10, 0x6b, 0x65,
	0x79, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x6b, 0x65, 0x79, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x18, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x29, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x73, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x63, 0x73, 0x72, 0x22, 0x3a, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x63, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x32, 0xf8, 0x05, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x12, 0x5e, 0x0a, 0x11, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x50, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x12, 0x22, 0x2e, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x50, 0x6c,
	0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x43, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x45, 0x4b, 0x12,
	0x18, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x45, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x45, 0x4b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x07, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x41,
	0x4b, 0x12, 0x18, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66,
	0x65, 0x72, 0x41, 0x4b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x41, 0x4b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d,
	0x61, 0x6b, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x12, 0x22, 0x2e,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x61, 0x6b, 0x65,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x23, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74,
	0x4d, 0x61, 0x6b, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x12, 0x26, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x76, 0x65, 0x72, 0x69,
	0x66, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0a, 0x4f, 0x66, 0x66, 0x65, 0x72, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x12, 0x1b, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x4f, 0x66,
	0x66, 0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x4f, 0x66, 0x66, 0x65, 0x72,
	0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x19, 0x2e, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x73,
	0x74, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x72, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4b, 0x65, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x41, 0x74, 0x74, 0x65, 0x73, 0x74, 0x65, 0x64, 0x4b, 0x65,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x65, 0x72,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x61, 0x6c, 0x72, 0x61, 0x73, 0x68, 0x69, 0x64, 0x31, 0x32, 0x33, 0x2f, 0x67, 0x6f,
	0x5f, 0x74, 0x70, 0x6d, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x65,
	0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_verifier_verifier_proto_rawDescOnce sync.Once
	file_src_verifier_verifier_proto_rawDescData = file_src_verifier_verifier_proto_rawDesc
)

func file_src_verifier_verifier_proto_rawDescGZIP() []byte {
	file_src_verifier_verifier_proto_rawDescOnce.Do(func() {
		file_src_verifier_verifier_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_verifier_verifier_proto_rawDescData)
	})
	return file_src_verifier_verifier_proto_rawDescData
}

var file_src_verifier_verifier_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_src_verifier_verifier_proto_goTypes = []interface{}{
	(*OfferPlatformCertRequest)(nil),      // 0: verifier.OfferPlatformCertRequest
	(*OfferPlatformCertResponse)(nil),     // 1: verifier.OfferPlatformCertResponse
	(*OfferEKRequest)(nil),                // 2: verifier.OfferEKRequest
	(*OfferEKResponse)(nil),               // 3: verifier.OfferEKResponse
	(*OfferAKRequest)(nil),                // 4: verifier.OfferAKRequest
	(*OfferAKResponse)(nil),               // 5: verifier.OfferAKResponse
	(*GetMakeCredentialRequest)(nil),      // 6: verifier.GetMakeCredentialRequest
	(*GetMakeCredentialResponse)(nil),     // 7: verifier.GetMakeCredentialResponse
	(*SetActivateCredentialRequest)(nil),  // 8: verifier.SetActivateCredentialRequest
	(*SetActivateCredentialResponse)(nil), // 9: verifier.SetActivateCredentialResponse
	(*OfferQuoteRequest)(nil),             // 10: verifier.OfferQuoteRequest
	(*OfferQuoteResponse)(nil),            // 11: verifier.OfferQuoteResponse
	(*SetQuoteRequest)(nil),               // 12: verifier.SetQuoteRequest
	(*SetQuoteResponse)(nil),              // 13: verifier.SetQuoteResponse
	(*SetAttestedKeyRequest)(nil),         // 14: verifier.SetAttestedKeyRequest
	(*SetAttestedKeyResponse)(nil),        // 15: verifier.SetAttestedKeyResponse
	(*GetCertificateRequest)(nil),         // 16: verifier.GetCertificateRequest
	(*GetCertificateResponse)(nil),        // 17: verifier.GetCertificateResponse
}
var file_src_verifier_verifier_proto_depIdxs = []int32{
	0,  // 0: verifier.Verifier.OfferPlatformCert:input_type -> verifier.OfferPlatformCertRequest
	2,  // 1: verifier.Verifier.OfferEK:input_type -> verifier.OfferEKRequest
	4,  // 2: verifier.Verifier.OfferAK:input_type -> verifier.OfferAKRequest
	6,  // 3: verifier.Verifier.GetMakeCredential:input_type -> verifier.GetMakeCredentialRequest
	8,  // 4: verifier.Verifier.SetActivateCredential:input_type -> verifier.SetActivateCredentialRequest
	10, // 5: verifier.Verifier.OfferQuote:input_type -> verifier.OfferQuoteRequest
	12, // 6: verifier.Verifier.SetQuote:input_type -> verifier.SetQuoteRequest
	14, // 7: verifier.Verifier.SetAttestedKey:input_type -> verifier.SetAttestedKeyRequest
	16, // 8: verifier.Verifier.GetCertificate:input_type -> verifier.GetCertificateRequest
	1,  // 9: verifier.Verifier.OfferPlatformCert:output_type -> verifier.OfferPlatformCertResponse
	3,  // 10: verifier.Verifier.OfferEK:output_type -> verifier.OfferEKResponse
	5,  // 11: verifier.Verifier.OfferAK:output_type -> verifier.OfferAKResponse
	7,  // 12: verifier.Verifier.GetMakeCredential:output_type -> verifier.GetMakeCredentialResponse
	9,  // 13: verifier.Verifier.SetActivateCredential:output_type -> verifier.SetActivateCredentialResponse
	11, // 14: verifier.Verifier.OfferQuote:output_type -> verifier.OfferQuoteResponse
	13, // 15: verifier.Verifier.SetQuote:output_type -> verifier.SetQuoteResponse
	15, // 16: verifier.Verifier.SetAttestedKey:output_type -> verifier.SetAttestedKeyResponse
	17, // 17: verifier.Verifier.GetCertificate:output_type -> verifier.GetCertificateResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_src_verifier_verifier_proto_init() }
func file_src_verifier_verifier_proto_init() {
	if File_src_verifier_verifier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_verifier_verifier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferPlatformCertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferPlatformCertResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferEKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferEKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferAKRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferAKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMakeCredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMakeCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetActivateCredentialRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetActivateCredentialResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferQuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfferQuoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetQuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetQuoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAttestedKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetAttestedKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCertificateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_verifier_verifier_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCertificateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_verifier_verifier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_verifier_verifier_proto_goTypes,
		DependencyIndexes: file_src_verifier_verifier_proto_depIdxs,
		MessageInfos:      file_src_verifier_verifier_proto_msgTypes,
	}.Build()
	File_src_verifier_verifier_proto = out.File
	file_src_verifier_verifier_proto_rawDesc = nil
	file_src_verifier_verifier_proto_goTypes = nil
	file_src_verifier_verifier_proto_depIdxs = nil
}
