syntax = "proto3";

package verifier;

option go_package = "github.com/salrashid123/go_tpm_remote_attestation/verifier";

service Verifier {
  rpc OfferPlatformCert (OfferPlatformCertRequest) returns (OfferPlatformCertResponse) { }
  rpc OfferEK (OfferEKRequest) returns (OfferEKResponse) { }
  rpc OfferAK (OfferAKRequest) returns (OfferAKResponse) { }      
  rpc GetMakeCredential (GetMakeCredentialRequest) returns (GetMakeCredentialResponse) { }
  rpc SetActivateCredential (SetActivateCredentialRequest) returns (SetActivateCredentialResponse) { }  
  rpc OfferQuote (OfferQuoteRequest) returns (OfferQuoteResponse) { }
  rpc SetQuote (SetQuoteRequest) returns (SetQuoteResponse) { }   
  rpc SetAttestedKey (SetAttestedKeyRequest) returns (SetAttestedKeyResponse) { }
  rpc GetCertificate (GetCertificateRequest) returns (GetCertificateResponse) { }        
}

message OfferPlatformCertRequest {
  bytes platformCert = 1;  
}

message OfferPlatformCertResponse {}

message OfferEKRequest {
  bytes ekCert = 1;  
}

message OfferEKResponse {}

message OfferAKRequest {
  bytes attestation_parameters = 1;  
}

message OfferAKResponse {}

message GetMakeCredentialRequest {}

message GetMakeCredentialResponse {
    bytes encrypted_credentials = 1;  
}

message SetActivateCredentialRequest {
  bytes secret = 1;  
}

message SetActivateCredentialResponse {}

message OfferQuoteRequest {}

message OfferQuoteResponse {
  bytes nonce = 1;
}

message SetQuoteRequest {
  bytes platform_attestation = 1;
}

message SetQuoteResponse {}

message SetAttestedKeyRequest {
  bytes key = 1;
  bytes keyCertification = 2;
}

message SetAttestedKeyResponse {}

message GetCertificateRequest {
  bytes csr = 1;
}

message GetCertificateResponse {
  bytes certificate = 1;
}