// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: src/verifier/verifier.proto

package verifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Verifier_OfferPlatformCert_FullMethodName     = "/verifier.Verifier/OfferPlatformCert"
	Verifier_OfferEK_FullMethodName               = "/verifier.Verifier/OfferEK"
	Verifier_OfferAK_FullMethodName               = "/verifier.Verifier/OfferAK"
	Verifier_GetMakeCredential_FullMethodName     = "/verifier.Verifier/GetMakeCredential"
	Verifier_SetActivateCredential_FullMethodName = "/verifier.Verifier/SetActivateCredential"
	Verifier_OfferQuote_FullMethodName            = "/verifier.Verifier/OfferQuote"
	Verifier_SetQuote_FullMethodName              = "/verifier.Verifier/SetQuote"
	Verifier_SetAttestedKey_FullMethodName        = "/verifier.Verifier/SetAttestedKey"
	Verifier_GetCertificate_FullMethodName        = "/verifier.Verifier/GetCertificate"
)

// VerifierClient is the client API for Verifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifierClient interface {
	OfferPlatformCert(ctx context.Context, in *OfferPlatformCertRequest, opts ...grpc.CallOption) (*OfferPlatformCertResponse, error)
	OfferEK(ctx context.Context, in *OfferEKRequest, opts ...grpc.CallOption) (*OfferEKResponse, error)
	OfferAK(ctx context.Context, in *OfferAKRequest, opts ...grpc.CallOption) (*OfferAKResponse, error)
	GetMakeCredential(ctx context.Context, in *GetMakeCredentialRequest, opts ...grpc.CallOption) (*GetMakeCredentialResponse, error)
	SetActivateCredential(ctx context.Context, in *SetActivateCredentialRequest, opts ...grpc.CallOption) (*SetActivateCredentialResponse, error)
	OfferQuote(ctx context.Context, in *OfferQuoteRequest, opts ...grpc.CallOption) (*OfferQuoteResponse, error)
	SetQuote(ctx context.Context, in *SetQuoteRequest, opts ...grpc.CallOption) (*SetQuoteResponse, error)
	SetAttestedKey(ctx context.Context, in *SetAttestedKeyRequest, opts ...grpc.CallOption) (*SetAttestedKeyResponse, error)
	GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error)
}

type verifierClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierClient(cc grpc.ClientConnInterface) VerifierClient {
	return &verifierClient{cc}
}

func (c *verifierClient) OfferPlatformCert(ctx context.Context, in *OfferPlatformCertRequest, opts ...grpc.CallOption) (*OfferPlatformCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferPlatformCertResponse)
	err := c.cc.Invoke(ctx, Verifier_OfferPlatformCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) OfferEK(ctx context.Context, in *OfferEKRequest, opts ...grpc.CallOption) (*OfferEKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferEKResponse)
	err := c.cc.Invoke(ctx, Verifier_OfferEK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) OfferAK(ctx context.Context, in *OfferAKRequest, opts ...grpc.CallOption) (*OfferAKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferAKResponse)
	err := c.cc.Invoke(ctx, Verifier_OfferAK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) GetMakeCredential(ctx context.Context, in *GetMakeCredentialRequest, opts ...grpc.CallOption) (*GetMakeCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMakeCredentialResponse)
	err := c.cc.Invoke(ctx, Verifier_GetMakeCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) SetActivateCredential(ctx context.Context, in *SetActivateCredentialRequest, opts ...grpc.CallOption) (*SetActivateCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetActivateCredentialResponse)
	err := c.cc.Invoke(ctx, Verifier_SetActivateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) OfferQuote(ctx context.Context, in *OfferQuoteRequest, opts ...grpc.CallOption) (*OfferQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OfferQuoteResponse)
	err := c.cc.Invoke(ctx, Verifier_OfferQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) SetQuote(ctx context.Context, in *SetQuoteRequest, opts ...grpc.CallOption) (*SetQuoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetQuoteResponse)
	err := c.cc.Invoke(ctx, Verifier_SetQuote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) SetAttestedKey(ctx context.Context, in *SetAttestedKeyRequest, opts ...grpc.CallOption) (*SetAttestedKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAttestedKeyResponse)
	err := c.cc.Invoke(ctx, Verifier_SetAttestedKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) GetCertificate(ctx context.Context, in *GetCertificateRequest, opts ...grpc.CallOption) (*GetCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCertificateResponse)
	err := c.cc.Invoke(ctx, Verifier_GetCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServer is the server API for Verifier service.
// All implementations should embed UnimplementedVerifierServer
// for forward compatibility.
type VerifierServer interface {
	OfferPlatformCert(context.Context, *OfferPlatformCertRequest) (*OfferPlatformCertResponse, error)
	OfferEK(context.Context, *OfferEKRequest) (*OfferEKResponse, error)
	OfferAK(context.Context, *OfferAKRequest) (*OfferAKResponse, error)
	GetMakeCredential(context.Context, *GetMakeCredentialRequest) (*GetMakeCredentialResponse, error)
	SetActivateCredential(context.Context, *SetActivateCredentialRequest) (*SetActivateCredentialResponse, error)
	OfferQuote(context.Context, *OfferQuoteRequest) (*OfferQuoteResponse, error)
	SetQuote(context.Context, *SetQuoteRequest) (*SetQuoteResponse, error)
	SetAttestedKey(context.Context, *SetAttestedKeyRequest) (*SetAttestedKeyResponse, error)
	GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error)
}

// UnimplementedVerifierServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVerifierServer struct{}

func (UnimplementedVerifierServer) OfferPlatformCert(context.Context, *OfferPlatformCertRequest) (*OfferPlatformCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OfferPlatformCert not implemented")
}
func (UnimplementedVerifierServer) OfferEK(context.Context, *OfferEKRequest) (*OfferEKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OfferEK not implemented")
}
func (UnimplementedVerifierServer) OfferAK(context.Context, *OfferAKRequest) (*OfferAKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OfferAK not implemented")
}
func (UnimplementedVerifierServer) GetMakeCredential(context.Context, *GetMakeCredentialRequest) (*GetMakeCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMakeCredential not implemented")
}
func (UnimplementedVerifierServer) SetActivateCredential(context.Context, *SetActivateCredentialRequest) (*SetActivateCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetActivateCredential not implemented")
}
func (UnimplementedVerifierServer) OfferQuote(context.Context, *OfferQuoteRequest) (*OfferQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OfferQuote not implemented")
}
func (UnimplementedVerifierServer) SetQuote(context.Context, *SetQuoteRequest) (*SetQuoteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetQuote not implemented")
}
func (UnimplementedVerifierServer) SetAttestedKey(context.Context, *SetAttestedKeyRequest) (*SetAttestedKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAttestedKey not implemented")
}
func (UnimplementedVerifierServer) GetCertificate(context.Context, *GetCertificateRequest) (*GetCertificateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCertificate not implemented")
}
func (UnimplementedVerifierServer) testEmbeddedByValue() {}

// UnsafeVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifierServer will
// result in compilation errors.
type UnsafeVerifierServer interface {
	mustEmbedUnimplementedVerifierServer()
}

func RegisterVerifierServer(s grpc.ServiceRegistrar, srv VerifierServer) {
	// If the following call panics, it indicates UnimplementedVerifierServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Verifier_ServiceDesc, srv)
}

func _Verifier_OfferPlatformCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferPlatformCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferPlatformCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_OfferPlatformCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferPlatformCert(ctx, req.(*OfferPlatformCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_OfferEK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferEKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferEK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_OfferEK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferEK(ctx, req.(*OfferEKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_OfferAK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferAKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferAK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_OfferAK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferAK(ctx, req.(*OfferAKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_GetMakeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMakeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).GetMakeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_GetMakeCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).GetMakeCredential(ctx, req.(*GetMakeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_SetActivateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetActivateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).SetActivateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_SetActivateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).SetActivateCredential(ctx, req.(*SetActivateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_OfferQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_OfferQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferQuote(ctx, req.(*OfferQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_SetQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).SetQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_SetQuote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).SetQuote(ctx, req.(*SetQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_SetAttestedKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAttestedKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).SetAttestedKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_SetAttestedKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).SetAttestedKey(ctx, req.(*SetAttestedKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_GetCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).GetCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Verifier_GetCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).GetCertificate(ctx, req.(*GetCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Verifier_ServiceDesc is the grpc.ServiceDesc for Verifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Verifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verifier.Verifier",
	HandlerType: (*VerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OfferPlatformCert",
			Handler:    _Verifier_OfferPlatformCert_Handler,
		},
		{
			MethodName: "OfferEK",
			Handler:    _Verifier_OfferEK_Handler,
		},
		{
			MethodName: "OfferAK",
			Handler:    _Verifier_OfferAK_Handler,
		},
		{
			MethodName: "GetMakeCredential",
			Handler:    _Verifier_GetMakeCredential_Handler,
		},
		{
			MethodName: "SetActivateCredential",
			Handler:    _Verifier_SetActivateCredential_Handler,
		},
		{
			MethodName: "OfferQuote",
			Handler:    _Verifier_OfferQuote_Handler,
		},
		{
			MethodName: "SetQuote",
			Handler:    _Verifier_SetQuote_Handler,
		},
		{
			MethodName: "SetAttestedKey",
			Handler:    _Verifier_SetAttestedKey_Handler,
		},
		{
			MethodName: "GetCertificate",
			Handler:    _Verifier_GetCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/verifier/verifier.proto",
}
