// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package verifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VerifierClient is the client API for Verifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerifierClient interface {
	OfferPlatformCert(ctx context.Context, in *OfferPlatformCertRequest, opts ...grpc.CallOption) (*OfferPlatformCertResponse, error)
	MakeCredential(ctx context.Context, in *MakeCredentialRequest, opts ...grpc.CallOption) (*MakeCredentialResponse, error)
	ActivateCredential(ctx context.Context, in *ActivateCredentialRequest, opts ...grpc.CallOption) (*ActivateCredentialResponse, error)
	GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error)
	OfferQuote(ctx context.Context, in *OfferQuoteRequest, opts ...grpc.CallOption) (*OfferQuoteResponse, error)
	ProvideQuote(ctx context.Context, in *ProvideQuoteRequest, opts ...grpc.CallOption) (*ProvideQuoteResponse, error)
	OfferAttestation(ctx context.Context, in *OfferAttestationRequest, opts ...grpc.CallOption) (*OfferAttestationResponse, error)
	ProvideAttestation(ctx context.Context, in *ProvideAttestationRequest, opts ...grpc.CallOption) (*ProvideAttestationResponse, error)
	OfferCSR(ctx context.Context, in *OfferCSRRequest, opts ...grpc.CallOption) (*OfferCSRResponse, error)
}

type verifierClient struct {
	cc grpc.ClientConnInterface
}

func NewVerifierClient(cc grpc.ClientConnInterface) VerifierClient {
	return &verifierClient{cc}
}

func (c *verifierClient) OfferPlatformCert(ctx context.Context, in *OfferPlatformCertRequest, opts ...grpc.CallOption) (*OfferPlatformCertResponse, error) {
	out := new(OfferPlatformCertResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/OfferPlatformCert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) MakeCredential(ctx context.Context, in *MakeCredentialRequest, opts ...grpc.CallOption) (*MakeCredentialResponse, error) {
	out := new(MakeCredentialResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/MakeCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) ActivateCredential(ctx context.Context, in *ActivateCredentialRequest, opts ...grpc.CallOption) (*ActivateCredentialResponse, error) {
	out := new(ActivateCredentialResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/ActivateCredential", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) GetSecret(ctx context.Context, in *GetSecretRequest, opts ...grpc.CallOption) (*GetSecretResponse, error) {
	out := new(GetSecretResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/GetSecret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) OfferQuote(ctx context.Context, in *OfferQuoteRequest, opts ...grpc.CallOption) (*OfferQuoteResponse, error) {
	out := new(OfferQuoteResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/OfferQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) ProvideQuote(ctx context.Context, in *ProvideQuoteRequest, opts ...grpc.CallOption) (*ProvideQuoteResponse, error) {
	out := new(ProvideQuoteResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/ProvideQuote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) OfferAttestation(ctx context.Context, in *OfferAttestationRequest, opts ...grpc.CallOption) (*OfferAttestationResponse, error) {
	out := new(OfferAttestationResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/OfferAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) ProvideAttestation(ctx context.Context, in *ProvideAttestationRequest, opts ...grpc.CallOption) (*ProvideAttestationResponse, error) {
	out := new(ProvideAttestationResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/ProvideAttestation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verifierClient) OfferCSR(ctx context.Context, in *OfferCSRRequest, opts ...grpc.CallOption) (*OfferCSRResponse, error) {
	out := new(OfferCSRResponse)
	err := c.cc.Invoke(ctx, "/verifier.Verifier/OfferCSR", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerifierServer is the server API for Verifier service.
// All implementations should embed UnimplementedVerifierServer
// for forward compatibility
type VerifierServer interface {
	OfferPlatformCert(context.Context, *OfferPlatformCertRequest) (*OfferPlatformCertResponse, error)
	MakeCredential(context.Context, *MakeCredentialRequest) (*MakeCredentialResponse, error)
	ActivateCredential(context.Context, *ActivateCredentialRequest) (*ActivateCredentialResponse, error)
	GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error)
	OfferQuote(context.Context, *OfferQuoteRequest) (*OfferQuoteResponse, error)
	ProvideQuote(context.Context, *ProvideQuoteRequest) (*ProvideQuoteResponse, error)
	OfferAttestation(context.Context, *OfferAttestationRequest) (*OfferAttestationResponse, error)
	ProvideAttestation(context.Context, *ProvideAttestationRequest) (*ProvideAttestationResponse, error)
	OfferCSR(context.Context, *OfferCSRRequest) (*OfferCSRResponse, error)
}

// UnimplementedVerifierServer should be embedded to have forward compatible implementations.
type UnimplementedVerifierServer struct {
}

func (UnimplementedVerifierServer) OfferPlatformCert(context.Context, *OfferPlatformCertRequest) (*OfferPlatformCertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferPlatformCert not implemented")
}
func (UnimplementedVerifierServer) MakeCredential(context.Context, *MakeCredentialRequest) (*MakeCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeCredential not implemented")
}
func (UnimplementedVerifierServer) ActivateCredential(context.Context, *ActivateCredentialRequest) (*ActivateCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateCredential not implemented")
}
func (UnimplementedVerifierServer) GetSecret(context.Context, *GetSecretRequest) (*GetSecretResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSecret not implemented")
}
func (UnimplementedVerifierServer) OfferQuote(context.Context, *OfferQuoteRequest) (*OfferQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferQuote not implemented")
}
func (UnimplementedVerifierServer) ProvideQuote(context.Context, *ProvideQuoteRequest) (*ProvideQuoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvideQuote not implemented")
}
func (UnimplementedVerifierServer) OfferAttestation(context.Context, *OfferAttestationRequest) (*OfferAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferAttestation not implemented")
}
func (UnimplementedVerifierServer) ProvideAttestation(context.Context, *ProvideAttestationRequest) (*ProvideAttestationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvideAttestation not implemented")
}
func (UnimplementedVerifierServer) OfferCSR(context.Context, *OfferCSRRequest) (*OfferCSRResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OfferCSR not implemented")
}

// UnsafeVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerifierServer will
// result in compilation errors.
type UnsafeVerifierServer interface {
	mustEmbedUnimplementedVerifierServer()
}

func RegisterVerifierServer(s grpc.ServiceRegistrar, srv VerifierServer) {
	s.RegisterService(&Verifier_ServiceDesc, srv)
}

func _Verifier_OfferPlatformCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferPlatformCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferPlatformCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/OfferPlatformCert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferPlatformCert(ctx, req.(*OfferPlatformCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_MakeCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).MakeCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/MakeCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).MakeCredential(ctx, req.(*MakeCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_ActivateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).ActivateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/ActivateCredential",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).ActivateCredential(ctx, req.(*ActivateCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_GetSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).GetSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/GetSecret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).GetSecret(ctx, req.(*GetSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_OfferQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/OfferQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferQuote(ctx, req.(*OfferQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_ProvideQuote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvideQuoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).ProvideQuote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/ProvideQuote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).ProvideQuote(ctx, req.(*ProvideQuoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_OfferAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/OfferAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferAttestation(ctx, req.(*OfferAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_ProvideAttestation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvideAttestationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).ProvideAttestation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/ProvideAttestation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).ProvideAttestation(ctx, req.(*ProvideAttestationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Verifier_OfferCSR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OfferCSRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerifierServer).OfferCSR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.Verifier/OfferCSR",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerifierServer).OfferCSR(ctx, req.(*OfferCSRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Verifier_ServiceDesc is the grpc.ServiceDesc for Verifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Verifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verifier.Verifier",
	HandlerType: (*VerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OfferPlatformCert",
			Handler:    _Verifier_OfferPlatformCert_Handler,
		},
		{
			MethodName: "MakeCredential",
			Handler:    _Verifier_MakeCredential_Handler,
		},
		{
			MethodName: "ActivateCredential",
			Handler:    _Verifier_ActivateCredential_Handler,
		},
		{
			MethodName: "GetSecret",
			Handler:    _Verifier_GetSecret_Handler,
		},
		{
			MethodName: "OfferQuote",
			Handler:    _Verifier_OfferQuote_Handler,
		},
		{
			MethodName: "ProvideQuote",
			Handler:    _Verifier_ProvideQuote_Handler,
		},
		{
			MethodName: "OfferAttestation",
			Handler:    _Verifier_OfferAttestation_Handler,
		},
		{
			MethodName: "ProvideAttestation",
			Handler:    _Verifier_ProvideAttestation_Handler,
		},
		{
			MethodName: "OfferCSR",
			Handler:    _Verifier_OfferCSR_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/verifier/verifier.proto",
}
